### ISSUE TITLE
Exception in thread "main" ... Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/IGUANA#55]
Hi,

when trying to run the latest IGUANA 1.1.0 with `java -cp "iguana-jars/*" org.aksw.iguana.benchmark.Main config.xml` it throws the following error:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/aksw/iguana/benchmark/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

```
I guess it's something with my java version (or the used compiler). My java is:

```
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

**Comment by simeonackermann** [comment]
Seems to be fixed by using newer JDK 8

**Comment by TortugaAttack** [comment]
Yep. Its upgraded to java 8, i will add it to the readme ;)
