### ISSUE TITLE
Several java.lang.NumberFormatException

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/IGUANA#56]
IGUANA 1.1.0 throws some exceptions when saving the results:

```
[INFO  Tue Jul 05 08:16:38 UTC 2016] StressTestcase ended at: 08:16:38::220 05.06.2016
[INFO  Tue Jul 05 08:16:38 UTC 2016] StressTestcase took 10m 33ms
[SEVERE  Tue Jul 05 08:16:38 UTC 2016] Result size differs!!! 
[SEVERE  Tue Jul 05 08:16:38 UTC 2016] Old size : 18
[SEVERE  Tue Jul 05 08:16:38 UTC 2016] New size: 0
java.lang.NumberFormatException: For input string: "643_min"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.aksw.iguana.utils.comparator.ResultSorting.produceMapping(ResultSorting.java:27)
	at org.aksw.iguana.utils.ResultSet.save(ResultSet.java:293)
	at org.aksw.iguana.testcases.StressTestcase.saveResults(StressTestcase.java:160)
	at org.aksw.iguana.testcases.StressTestcase.start(StressTestcase.java:132)
	at org.aksw.iguana.benchmark.processor.TestcaseProcessor.testTestcase(TestcaseProcessor.java:196)
	at org.aksw.iguana.benchmark.Benchmark.start(Benchmark.java:177)
	at org.aksw.iguana.benchmark.Benchmark.execute(Benchmark.java:64)
	at org.aksw.iguana.benchmark.Main.main(Main.java:57)
java.lang.NumberFormatException: For input string: "643_min"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.aksw.iguana.utils.comparator.ResultSorting.produceMapping(ResultSorting.java:27)
	at org.aksw.iguana.utils.ResultSet.save(ResultSet.java:293)
	at org.aksw.iguana.testcases.StressTestcase.saveResults(StressTestcase.java:160)
	at org.aksw.iguana.testcases.StressTestcase.start(StressTestcase.java:132)
	at org.aksw.iguana.benchmark.processor.TestcaseProcessor.testTestcase(TestcaseProcessor.java:196)
	at org.aksw.iguana.benchmark.Benchmark.start(Benchmark.java:177)
	at org.aksw.iguana.benchmark.Benchmark.execute(Benchmark.java:64)
	at org.aksw.iguana.benchmark.Main.main(Main.java:57)
java.lang.NumberFormatException: For input string: "643_min"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.aksw.iguana.utils.comparator.ResultSorting.produceMapping(ResultSorting.java:27)
	at org.aksw.iguana.utils.ResultSet.save(ResultSet.java:293)
	at org.aksw.iguana.testcases.StressTestcase.saveResults(StressTestcase.java:160)
	at org.aksw.iguana.testcases.StressTestcase.start(StressTestcase.java:132)
	at org.aksw.iguana.benchmark.processor.TestcaseProcessor.testTestcase(TestcaseProcessor.java:196)
	at org.aksw.iguana.benchmark.Benchmark.start(Benchmark.java:177)
	at org.aksw.iguana.benchmark.Benchmark.execute(Benchmark.java:64)
	at org.aksw.iguana.benchmark.Main.main(Main.java:57)
[INFO  Tue Jul 05 08:16:38 UTC 2016] StressTestcase finished
[INFO  Tue Jul 05 08:16:38 UTC 2016] Stopping testcase org.aksw.iguana.testcases.StressTestcase at: 08:16:38::472 05.06.2016
[INFO  Tue Jul 05 08:16:38 UTC 2016] Testcase took 10m 346ms
[INFO  Tue Jul 05 08:16:38 UTC 2016] Starting Garbage Collector
[INFO  Tue Jul 05 08:16:38 UTC 2016] Finished Garbage Collector
[INFO  Tue Jul 05 08:16:38 UTC 2016] Suite ended at: 08:16:38::601 05.06.2016
[INFO  Tue Jul 05 08:16:38 UTC 2016] Suite took 10m 487ms
[INFO  Tue Jul 05 08:16:38 UTC 2016] Saving Results for org.aksw.iguana.testcases.StressTestcase&0&1.0...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/Failed_Queries_SPARQL Worker0 ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/calculated/Failed_Queries_SPARQL Worker_Mean ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/calculated/Failed_Queries_SPARQL Worker_Sum ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/Queries_Min-and-Max_SPARQL Worker0 ...
java.lang.NumberFormatException: For input string: "643_min"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.aksw.iguana.utils.comparator.ResultSorting.produceMapping(ResultSorting.java:27)
	at org.aksw.iguana.utils.ResultSet.save(ResultSet.java:293)
	at org.aksw.iguana.benchmark.processor.ResultProcessor.saveResults(ResultProcessor.java:181)
	at org.aksw.iguana.benchmark.Benchmark.post(Benchmark.java:100)
	at org.aksw.iguana.benchmark.Benchmark.execute(Benchmark.java:66)
	at org.aksw.iguana.benchmark.Main.main(Main.java:57)
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/calculated/Queries_Min-and-Max_SPARQL Worker_Mean ...
java.lang.NumberFormatException: For input string: "643_min"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.aksw.iguana.utils.comparator.ResultSorting.produceMapping(ResultSorting.java:27)
	at org.aksw.iguana.utils.ResultSet.save(ResultSet.java:293)
	at org.aksw.iguana.benchmark.processor.ResultProcessor.saveResults(ResultProcessor.java:181)
	at org.aksw.iguana.benchmark.Benchmark.post(Benchmark.java:100)
	at org.aksw.iguana.benchmark.Benchmark.execute(Benchmark.java:66)
	at org.aksw.iguana.benchmark.Main.main(Main.java:57)
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/calculated/Queries_Min-and-Max_SPARQL Worker_Sum ...
java.lang.NumberFormatException: For input string: "643_min"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.aksw.iguana.utils.comparator.ResultSorting.produceMapping(ResultSorting.java:27)
	at org.aksw.iguana.utils.ResultSet.save(ResultSet.java:293)
	at org.aksw.iguana.benchmark.processor.ResultProcessor.saveResults(ResultProcessor.java:181)
	at org.aksw.iguana.benchmark.Benchmark.post(Benchmark.java:100)
	at org.aksw.iguana.benchmark.Benchmark.execute(Benchmark.java:66)
	at org.aksw.iguana.benchmark.Main.main(Main.java:57)
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/Queries_Mixes_Per_TimeLimit_SPARQL Worker0 ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/calculated/Queries_Mixes_Per_TimeLimit_SPARQL Worker_Mean ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/calculated/Queries_Mixes_Per_TimeLimit_SPARQL Worker_Sum ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/Queries_Per_Second_SPARQL Worker0 ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/calculated/Queries_Per_Second_SPARQL Worker_Mean ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/calculated/Queries_Per_Second_SPARQL Worker_Sum ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/Queries_Totaltime_SPARQL Worker0 ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/calculated/Queries_Totaltime_SPARQL Worker_Mean ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/calculated/Queries_Totaltime_SPARQL Worker_Sum ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/Succeded_Queries_SPARQL Worker0 ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/calculated/Succeded_Queries_SPARQL Worker_Mean ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ... save ./results_0/org.aksw.iguana.testcases.StressTestcase1.0/1/0/calculated/Succeded_Queries_SPARQL Worker_Sum ...
[INFO  Tue Jul 05 08:16:38 UTC 2016] ...finished saving results for org.aksw.iguana.testcases.StressTestcase&0&1.0

```

**Comment by TortugaAttack** [comment]
Oh those are just for debugging. I forgot to comment them out. 
Its fine, the csv is just not sorted like 1_min, 1_max, 2_min, 2_max and so on. 
but thanks :) 

Oh, but something is wondering me: why 643_min? 
Do you use a query instance file called 643.txt? 
or do you use more than 600 queries?

**Comment by simeonackermann** [comment]
Yep, I'm using 1000 queries ;)

Another test with just 2 queries gives a `0_min`

**Comment by TortugaAttack** [comment]
ah okay :) 
nice.

Okay i will exclude the output, but for now just ignore it if it is not to annoying ;)

**Comment by simeonackermann** [comment]
Thanks!
To know that's not corrupts the results is fine enough!
