### ISSUE TITLE
NullPointer Exception

### ISSUE THREAD

**Issue by earthquakesan** [AKSW/IGUANA#69]
```
[SEVERE  Sat Sep 30 14:09:53 CEST 2017] Couldn't test testcase org.aksw.iguana.testcases.StressTestcase&0 due to:
[SEVERE  Sat Sep 30 14:09:53 CEST 2017] java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at java.util.Properties.setProperty(Properties.java:166)
	at org.aksw.iguana.testcases.StressTestcase.setProperties(StressTestcase.java:728)
	at org.aksw.iguana.benchmark.processor.TestcaseProcessor.testTestcase(TestcaseProcessor.java:178)
	at org.aksw.iguana.benchmark.Benchmark.start(Benchmark.java:177)
	at org.aksw.iguana.benchmark.Benchmark.execute(Benchmark.java:64)
	at org.aksw.iguana.benchmark.Main.main(Main.java:57)
```

How to address this?

**Comment by TortugaAttack** [comment]
What is your exact config?
It seems that a stresstest property is missing.
Have a look here http://iguana-benchmark.eu/gettingstarted.html#stresstestcase

**Comment by earthquakesan** [comment]
I grabbed and modified this [one](https://figshare.com/articles/Configuration_DBpedia_100_/3205465)

Here is the full configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<iguana xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <databases main="dbpedia">
    <database id="halyard" type="impl">
      <endpoint uri="http://halyard.eval.aksw.org/rdf4j-server/repositories/benchmark10"/>
      <!--update-endpoint uri="http://halyard.eval.aksw.org/rdf4j-server/repositories/benchmark10"/-->
    </database>
    <database id="ref" type="impl">
      <endpoint uri="http://dbpedia.org/sparql"/>
    </database>
  </databases>
  <suite>
    <drop-db value="false"/>
    <query-diversity value="2000"/>
    <!--graph-uri name="http://dbpedia.org"/-->
    <random-function type="RandomTriple" generate="false">
      <percent value="1.0" file-name="dbpedia/"/>
    </random-function>
    <number-of-triples value="9"/>
    <!--warmup time="20" file-name="configuration/warmup.txt"/-->
    <test-db type="choose" reference="ref">
      <db id="halyard"/>
    </test-db>
    <!--testcases testcase-pre="./scripts/swdf_pre.sh %DBID% %PERCENT% %TESTCASEID%" testcase-post="./scripts/swdf_pre.sh"-->
    <testcases>
      <testcase class="org.aksw.iguana.testcases.StressTestcase">
        <property name="sparql-user" value="1"/>
        <property name="update-user" value="1"/>
        <property name="queries-path" value="configuration/Queries2.txt"/>
        <property name="update-path" value="configuration/changesets/dbpedia"/>
        <property name="is-pattern" value="false"/>
        <property name="linking-strategy" value="DI"/>
        <property name="update-strategy" value="VARIABLE"/>
        <property name="worker-strategy" value="NEXT"/>
        <property name="limit" value="2000"/>
        <property name="timelimit" value="3600000"/>
      </testcase>
      <testcase class="org.aksw.iguana.testcases.StressTestcase">
        <property name="sparql-user" value="1"/>
        <property name="update-user" value="0"/>
        <property name="is-pattern" value="false"/>
        <property name="queries-path" value="configuration/Queries2.txt"/>
        <property name="limit" value="2000"/>
        <property name="timelimit" value="3600000"/>
      </testcase>
      <testcase class="org.aksw.iguana.testcases.StressTestcase">
        <property name="sparql-user" value="2"/>
        <property name="update-user" value="0"/>
        <property name="is-pattern" value="false"/>
        <property name="queries-path" value="configuration/Queries2.txt"/>
        <property name="limit" value="2000"/>
        <property name="timelimit" value="3600000"/>
      </testcase>
      <testcase class="org.aksw.iguana.testcases.StressTestcase">
        <property name="sparql-user" value="4"/>
        <property name="update-user" value="0"/>
        <property name="is-pattern" value="false"/>
        <property name="queries-path" value="configuration/Queries2.txt"/>
        <property name="limit" value="2000"/>
        <property name="timelimit" value="3600000"/>
      </testcase>
      <testcase class="org.aksw.iguana.testcases.StressTestcase">
        <property name="sparql-user" value="8"/>
        <property name="update-user" value="0"/>
        <property name="is-pattern" value="false"/>
        <property name="queries-path" value="configuration/Queries2.txt"/>
        <property name="limit" value="2000"/>
        <property name="timelimit" value="3600000"/>
      </testcase>
      <testcase class="org.aksw.iguana.testcases.StressTestcase">
        <property name="sparql-user" value="16"/>
        <property name="is-pattern" value="false"/>
        <property name="update-user" value="0"/>
        <property name="queries-path" value="configuration/Queries2.txt"/>
        <property name="update-path" value="configuration/changesets/dbpedia"/>
        <property name="linking-strategy" value="DI"/>
        <property name="update-strategy" value="VARIABLE"/>
        <property name="limit" value="2000"/>
        <property name="timelimit" value="3600000"/>
      </testcase>
      <testcase class="org.aksw.iguana.testcases.StressTestcase">
        <property name="sparql-user" value="2"/>
        <property name="update-user" value="1"/>
        <property name="queries-path" value="configuration/Queries2.txt"/>
        <property name="update-path" value="configuration/changesets/dbpedia"/>
        <property name="linking-strategy" value="DI"/>
        <property name="update-strategy" value="VARIABLE"/>
        <property name="is-pattern" value="false"/>
        <property name="worker-strategy0" value="NEXT"/>
        <property name="limit" value="2000"/>
        <property name="timelimit" value="3600000"/>
      </testcase>
      <testcase class="org.aksw.iguana.testcases.StressTestcase">
        <property name="sparql-user" value="4"/>
        <property name="update-user" value="1"/>
        <property name="queries-path" value="configuration/Queries2.txt"/>
        <property name="update-path" value="configuration/changesets/dbpedia"/>
        <property name="linking-strategy" value="DI"/>
        <property name="update-strategy" value="VARIABLE"/>
        <property name="is-pattern" value="false"/>
        <property name="worker-strategy0" value="NEXT"/>
        <property name="limit" value="2000"/>
        <property name="timelimit" value="3600000"/>
      </testcase>
      <testcase class="org.aksw.iguana.testcases.StressTestcase">
        <property name="sparql-user" value="8"/>
        <property name="update-user" value="1"/>
        <property name="queries-path" value="configuration/Queries2.txt"/>
        <property name="update-path" value="configuration/changesets/dbpedia"/>
        <property name="linking-strategy" value="DI"/>
        <property name="update-strategy" value="VARIABLE"/>
        <property name="is-pattern" value="false"/>
        <property name="worker-strategy0" value="NEXT"/>
        <property name="limit" value="2000"/>
        <property name="timelimit" value="3600000"/>
      </testcase>
      <testcase class="org.aksw.iguana.testcases.StressTestcase">
        <property name="sparql-user" value="16"/>
        <property name="update-user" value="1"/>
        <property name="queries-path" value="configuration/Queries2.txt"/>
        <property name="is-pattern" value="false"/>
        <property name="linking-strategy" value="DI"/>
        <property name="update-path" value="configuration/changesets/dbpedia"/>
        <property name="worker-strategy0" value="NEXT"/>
        <property name="update-strategy" value="VARIABLE"/>
        <property name="timelimit" value="3600000"/>
      </testcase>
    </testcases>
  </suite>
</iguana>
```

P.S. Endpoint is public now, you should be able to run it from your PC.

**Comment by earthquakesan** [comment]
I used [dbpedia queries](https://figshare.com/articles/Queries_DBpedia/3205477), and these [changesets](https://figshare.com/articles/Changesets_DBpedia/3205471).

**Comment by TortugaAttack** [comment]
hmm the error does not make sense. 
https://github.com/AKSW/IGUANA/blob/Version1.x/org.aksw.iguana/src/main/java/org/aksw/iguana/testcases/StressTestcase.java#L728
it is not setProperty. 
I will debug the issue on Monday. :/

**Comment by TortugaAttack** [comment]
problem is the `is-pattern` value. It must be true. 
Will close this issue now as this is a known issue and will be challenged in the next version
